#vim: set ft=yml sw=2 ts=2 sts=2 et tw=78

version: '2'
services:
  db:
    image: postgis/postgis:12-3.0
    ports:
     - "5432:5432"
    environment:
     - DB_NAME=crowdfiller
     - DB_USER=crowdfiller
     - DB_PASS=crowdfiller
     - POSTGRES_PASSWORD=crowdfiller
     - POSTGRES_USER=crowdfiller

